// <auto-generated />
using System;
using Diary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diary.Migrations
{
    [DbContext(typeof(DiaryContext))]
    [Migration("20240810042530_AddedMoreSeedingDataDiariesEntry")]
    partial class AddedMoreSeedingDataDiariesEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.4.24267.1");

            modelBuilder.Entity("Diary.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is a seed data Test 1 content",
                            Created = new DateTime(2024, 8, 10, 16, 25, 30, 442, DateTimeKind.Local).AddTicks(9460),
                            Title = "Test 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "WEnt hiking with Joe",
                            Created = new DateTime(2024, 8, 10, 16, 25, 30, 442, DateTimeKind.Local).AddTicks(9460),
                            Title = "Went Hiking"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Went swimming with Miffy",
                            Created = new DateTime(2024, 8, 10, 16, 25, 30, 442, DateTimeKind.Local).AddTicks(9460),
                            Title = "Went Swimming"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
